name: ci
# Run on push to main and any pull request.
on:
  push:
    branches:
      - main
  pull_request:
env:
  CGO_ENABLED: 0
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v1.60.2
  SHELLCHECK_SCRIPTS: ./*.sh
jobs:
  go-lint-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
  go-mod-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Check if go.mod is tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum ||
            (echo "::error::go.mod and go.sum need to be tidy" && exit 1)
  go-linux:
      name: Run Go tests on Linux
      runs-on: ubuntu-latest
      steps:
        - name: Check out code
          uses: actions/checkout@v4
        - name: unittests
          run: go test -v -race ./...
